### ISSUE TITLE
Help completing this plugin

### ISSUE THREAD

**Issue by szepeviktor** [meilisearch/meilisearch-wordpress#16]
Hello! 👋 I could help finish meilisearch-wordpress if waving good-bye to PHP 4-like WordPress style is okay for you.
Here is what I'm talking about: the result of a research on main file parts.
https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md
There is some source code too in that repository.

What do you think?

**Comment by szepeviktor** [comment]
Please change "Wordpress" to "WordPress" in the About box here on GitHub :)

**Comment by eskombro** [comment]
Hi @szepeviktor !

Thanks a lot for offering some help! Indeed, this was a prototype to see how MeilISearch would work with WordPress but we haven't had enough time to make it evolve into a real plugin, so your help is more than welcome and appreciated! 🎉 

> Please change "Wordpress" to "WordPress" in the About box here on GitHub an other places :)
> It is highly ⚠️ important!

I started renaming it in the description and #17 :)

**Comment by curquiza** [comment]
Hello @szepeviktor!
Thanks for your involvement!! It would be awesome to work with you 😁

> Note: FYI our PHP SDK is tested to support versions 7.2, 7.3, 7.4 (and 8.0) and I see no problem in assuming PHP 7 as the base for the plugin, but what do you think @curquiza ?

PHP 7.2 has reached its EOL but we agreed to keep the support of PHP 7.2 anyway! See https://github.com/meilisearch/meilisearch-php/issues/136
So, for me, the minimal PHP version we support for this plugin should be PHP 7.2 🙂

Thanks again!!! 🎉

**Comment by szepeviktor** [comment]
All right!

What do you think about the research results linked above?

**Comment by curquiza** [comment]
> What do you think about the research results linked above?

I'm not sure to really understand what you mean about "research results"? I understand this is this file (https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md) but are they rules you would apply to this plugin? Is this file related to MeiliSearch research results?

**Comment by szepeviktor** [comment]
> are they rules you would apply to this plugin? Is this file related to MeiliSearch research results?

Yes, I'd refrain from writing globals: constants, functions, classes without namespace.

**Comment by curquiza** [comment]
Every "rule" introduction to this plugin would be nice, I don't think we have any for the moment, since it's a WIP! So feel free to bring any change, we will review it anyway 🙂

**Comment by szepeviktor** [comment]
As you asked your questions that note got completed with these:

### What to avoid

- Global constants
- Global functions
- Classes without namespace
- Loading PHP files with `require`
- Code with [side-effects](https://www.php-fig.org/psr/psr-1/#23-side-effects) outside the main file
- Immediate execution without `add_action` in the main file
- Conditional function or class definition

Thank you.

**Comment by szepeviktor** [comment]
Some tiny preview: https://gist.github.com/szepeviktor/a12b9a392793a0087ebad889bb2c7188

**Comment by szepeviktor** [comment]
Development continues 🚀 e.g. with a search for container ...
